BASE = '/home/yusongli/_dataset/shidaoai/img/_out/nn/DATASET/nnUNet_raw_data_base'
PREPROCESSING_OUTPUT_DIR = '/home/yusongli/_dataset/shidaoai/img/_out/nn/DATASET/nnUNet_preprocessed'
NETWORK_TRAINING_OUTPUT_DIR_BASE = '/home/yusongli/_dataset/shidaoai/img/_out/nn/DATASET/nnUNet_cropped_data'
VTUNET_RAW_DATA = '/home/yusongli/_dataset/shidaoai/img/_out/nn/DATASET/nnUNet_raw_data_base/nnUNet_raw_data'
VTUNET_CROPPED_DATA = '/home/yusongli/_dataset/shidaoai/img/_out/nn/DATASET/nnUNet_raw_data_base/nnUNet_cropped_data'
